"""Initial Prompt Library — 50 production-quality enterprise prompts
(spec section 56).

Each prompt follows the four-part framework (Goal / Context / Source /
Expectations) plus governance metadata, inputs, tags and productivity
estimates.
"""

PROMPTS: list[dict] = [
    # ── Outlook ─────────────────────────────────────────────────────────────
    {
        "name": "Executive Email Writer",
        "description": "Draft a professional, decision-focused email from briefing points.",
        "business_function": "EXECUTIVE",
        "application": "OUTLOOK",
        "task": "CREATE",
        "goal": "Draft a clear, professional email that conveys the key points and requested actions.",
        "context": "The email is sent on behalf of a senior manager at Contoso Financial Services and must be concise, courteous and decision-oriented.",
        "source": "Use only the supplied briefing points, recipients and desired outcome.",
        "expectations": "Produce a complete email with subject line, salutation, three-to-five concise paragraphs, a clear call to action, and professional closing.",
        "audience": "SENIOR_MANAGEMENT",
        "tone": "PROFESSIONAL",
        "output_format": "EMAIL",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["email", "executive", "communication"],
        "manual_time_minutes": 20,
        "ai_time_minutes": 3,
        "template": "To: {{recipients}}\n\nDraft an executive email from the following briefing:\n\n{{briefing_points}}\n\nThe desired outcome is: {{desired_outcome}}.",
        "inputs": [
            {
                "name": "recipients",
                "type": "TEXT",
                "required": True,
                "description": "Recipient names / group",
            },
            {
                "name": "briefing_points",
                "type": "TEXT",
                "required": True,
                "description": "Key points to convey",
            },
            {
                "name": "desired_outcome",
                "type": "TEXT",
                "required": True,
                "description": "Action you want the recipient to take",
            },
        ],
    },
    {
        "name": "Email Summariser",
        "description": "Condense an email thread into key messages and required actions.",
        "business_function": "OPERATIONS",
        "application": "OUTLOOK",
        "task": "SUMMARISE",
        "goal": "Summarise the email thread into key messages, decisions and actions.",
        "context": "Executives receive hundreds of emails daily; the summary must allow rapid triage.",
        "source": "Use only the supplied email thread.",
        "expectations": "Provide a 3-5 bullet summary, the main decision requested, and any deadlines or owners mentioned.",
        "audience": "MANAGEMENT",
        "tone": "CONCISE",
        "output_format": "BULLET_POINTS",
        "max_length": "SHORT",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["email", "summary"],
        "manual_time_minutes": 15,
        "ai_time_minutes": 2,
        "template": "Summarise the following email thread:\n\n{{email_thread}}",
        "inputs": [
            {
                "name": "email_thread",
                "type": "TEXT",
                "required": True,
                "description": "Paste the email thread",
            }
        ],
    },
    {
        "name": "Email Action Extractor",
        "description": "Extract actions, owners and deadlines from email correspondence.",
        "business_function": "PROJECT_MANAGEMENT",
        "application": "OUTLOOK",
        "task": "EXTRACT",
        "goal": "Extract all action items, owners, and deadlines from the supplied emails.",
        "context": "Project managers need to track commitments made across email without manual reading.",
        "source": "Use only the supplied email thread.",
        "expectations": "Return a table of actions with owner, due date, status and source email. Flag unclear owners.",
        "audience": "TEAM",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["email", "actions", "project"],
        "manual_time_minutes": 25,
        "ai_time_minutes": 4,
        "template": "Extract action items from the following emails:\n\n{{emails}}\n\nReturn each as: action, owner, due date, status.",
        "inputs": [
            {"name": "emails", "type": "TEXT", "required": True, "description": "Paste emails"}
        ],
    },
    {
        "name": "Email Priority Classifier",
        "description": "Classify inbox emails by priority for triage.",
        "business_function": "OPERATIONS",
        "application": "OUTLOOK",
        "task": "CLASSIFY",
        "goal": "Classify each email as HIGH, MEDIUM or LOW priority and explain why.",
        "context": "Support staff must prioritise a shared inbox; the classification should consider urgency, sender and action required.",
        "source": "Use only the supplied list of emails.",
        "expectations": "Return a table: email subject, sender, priority, confidence, rationale, recommended action.",
        "audience": "TEAM",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["email", "classification"],
        "manual_time_minutes": 15,
        "ai_time_minutes": 2,
        "template": "Classify the following emails by priority:\n\n{{emails}}",
        "inputs": [
            {"name": "emails", "type": "TEXT", "required": True, "description": "List of emails"}
        ],
    },
    {
        "name": "Professional Email Rewriter",
        "description": "Rewrite informal or unclear emails into professional corporate tone.",
        "business_function": "HR",
        "application": "OUTLOOK",
        "task": "REWRITE",
        "goal": "Rewrite the email into a clear, professional corporate message.",
        "context": "Communication quality reflects on the company; internal comms guidance prefers warm but professional tone.",
        "source": "Use only the supplied email text.",
        "expectations": "Preserve all meaning and facts, fix grammar, maintain the sender's intent, and note any content that is unclear.",
        "audience": "GENERAL",
        "tone": "PROFESSIONAL",
        "output_format": "EMAIL",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["email", "rewrite"],
        "manual_time_minutes": 10,
        "ai_time_minutes": 2,
        "template": "Rewrite the following email in a professional corporate tone:\n\n{{email}}",
        "inputs": [
            {"name": "email", "type": "TEXT", "required": True, "description": "Email to rewrite"}
        ],
    },
    {
        "name": "Customer Response Generator",
        "description": "Draft empathetic, resolution-oriented responses to customer enquiries.",
        "business_function": "CUSTOMER_SERVICE",
        "application": "OUTLOOK",
        "task": "CREATE",
        "goal": "Draft a courteous customer response that addresses the enquiry and offers a clear next step.",
        "context": "Responses represent Contoso's customer experience standard and must be empathetic and factual.",
        "source": "Use only the customer message and any account context provided.",
        "expectations": "Produce an email that acknowledges the issue, explains what happens next, and sets expectations on timing.",
        "audience": "CUSTOMER",
        "tone": "SUPPORTIVE",
        "output_format": "EMAIL",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "contains_pii": True,
        "tags": ["email", "customer", "support"],
        "manual_time_minutes": 20,
        "ai_time_minutes": 3,
        "template": "Draft a customer response to:\n\n{{customer_message}}\n\nAccount context: {{account_context}}",
        "inputs": [
            {
                "name": "customer_message",
                "type": "TEXT",
                "required": True,
                "description": "Customer message",
            },
            {
                "name": "account_context",
                "type": "TEXT",
                "required": False,
                "description": "Account context",
            },
        ],
    },
    {
        "name": "Follow-up Email Generator",
        "description": "Create polite follow-up emails for outstanding items.",
        "business_function": "PROJECT_MANAGEMENT",
        "application": "OUTLOOK",
        "task": "CREATE",
        "goal": "Generate a polite, professional follow-up email for an outstanding item.",
        "context": "Project follow-ups must be firm yet courteous and clearly reference the original request.",
        "source": "Use only the original request details and the outstanding item.",
        "expectations": "Produce an email that references the original item, the current status, the requested action and a deadline.",
        "audience": "TEAM",
        "tone": "PROFESSIONAL",
        "output_format": "EMAIL",
        "max_length": "SHORT",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["email", "follow-up"],
        "manual_time_minutes": 10,
        "ai_time_minutes": 2,
        "template": "Write a follow-up email about: {{outstanding_item}}\nOriginal request: {{original_request}}\nRecipient: {{recipient}}",
        "inputs": [
            {
                "name": "outstanding_item",
                "type": "TEXT",
                "required": True,
                "description": "Item to follow up",
            },
            {
                "name": "original_request",
                "type": "TEXT",
                "required": True,
                "description": "Original request",
            },
            {"name": "recipient", "type": "TEXT", "required": True, "description": "Recipient"},
        ],
    },
    {
        "name": "Meeting Follow-up Email",
        "description": "Send meeting notes and action items to attendees.",
        "business_function": "PROJECT_MANAGEMENT",
        "application": "OUTLOOK",
        "task": "CREATE",
        "goal": "Draft a meeting follow-up email that records notes, decisions and actions.",
        "context": "Attendees need an accurate record soon after the meeting to keep momentum.",
        "source": "Use only the supplied meeting notes.",
        "expectations": "Include the meeting title/date, key decisions, action items with owners and due dates, and the next meeting if known.",
        "audience": "TEAM",
        "tone": "PROFESSIONAL",
        "output_format": "EMAIL",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["email", "meeting", "notes"],
        "manual_time_minutes": 15,
        "ai_time_minutes": 3,
        "template": "Create a meeting follow-up email from these notes:\n\n{{meeting_notes}}",
        "inputs": [
            {
                "name": "meeting_notes",
                "type": "TEXT",
                "required": True,
                "description": "Meeting notes",
            }
        ],
    },
    # ── Teams ───────────────────────────────────────────────────────────────
    {
        "name": "Meeting Summary",
        "description": "Summarise a Teams meeting transcript into concise meeting notes.",
        "business_function": "PROJECT_MANAGEMENT",
        "application": "TEAMS",
        "task": "SUMMARISE",
        "goal": "Produce concise meeting notes from the transcript.",
        "context": "Teams meetings produce long transcripts; the summary supports fast recall and accountability.",
        "source": "Use only the supplied meeting transcript.",
        "expectations": "Provide: purpose, decisions, action items (owner/due), open questions and key risks. Keep under 300 words.",
        "audience": "TEAM",
        "tone": "CONCISE",
        "output_format": "ACTION_ITEMS",
        "max_length": "SHORT",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["teams", "meeting", "summary"],
        "manual_time_minutes": 20,
        "ai_time_minutes": 3,
        "template": "Summarise this meeting transcript:\n\n{{transcript}}",
        "inputs": [
            {
                "name": "transcript",
                "type": "TEXT",
                "required": True,
                "description": "Meeting transcript",
            }
        ],
    },
    {
        "name": "Meeting Actions",
        "description": "Extract action items and owners from meeting transcripts.",
        "business_function": "PROJECT_MANAGEMENT",
        "application": "TEAMS",
        "task": "EXTRACT",
        "goal": "Extract all action items, owners and deadlines from the meeting.",
        "context": "Meetings drift without captured actions; this turns transcript into an actionable list.",
        "source": "Use only the supplied transcript.",
        "expectations": "Return numbered actions with owner, due date, and the sentence it came from.",
        "audience": "TEAM",
        "tone": "ANALYTICAL",
        "output_format": "ACTION_ITEMS",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["teams", "actions"],
        "manual_time_minutes": 15,
        "ai_time_minutes": 2,
        "template": "Extract action items from this transcript:\n\n{{transcript}}",
        "inputs": [
            {
                "name": "transcript",
                "type": "TEXT",
                "required": True,
                "description": "Meeting transcript",
            }
        ],
    },
    {
        "name": "Meeting Decisions",
        "description": "Identify decisions made during a meeting.",
        "business_function": "PROJECT_MANAGEMENT",
        "application": "TEAMS",
        "task": "EXTRACT",
        "goal": "Identify all decisions made during the meeting.",
        "context": "Decision capture is critical for audit and accountability.",
        "source": "Use only the supplied transcript.",
        "expectations": "List each decision, who made/confirmed it, and the context sentence.",
        "audience": "MANAGEMENT",
        "tone": "CONCISE",
        "output_format": "BULLET_POINTS",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["teams", "decisions"],
        "manual_time_minutes": 15,
        "ai_time_minutes": 2,
        "template": "List the decisions made in this meeting:\n\n{{transcript}}",
        "inputs": [
            {
                "name": "transcript",
                "type": "TEXT",
                "required": True,
                "description": "Meeting transcript",
            }
        ],
    },
    {
        "name": "Meeting Risk Extractor",
        "description": "Extract risks mentioned in meeting conversations.",
        "business_function": "RISK",
        "application": "TEAMS",
        "task": "EXTRACT",
        "goal": "Extract risks, concerns and escalations from the meeting discussion.",
        "context": "Risk register should be fed from discussions, not just formal reports.",
        "source": "Use only the supplied transcript.",
        "expectations": "For each risk: description, severity (H/M/L), owner if mentioned, and context.",
        "audience": "MANAGEMENT",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "MEDIUM",
        "tags": ["teams", "risk"],
        "manual_time_minutes": 20,
        "ai_time_minutes": 3,
        "template": "Extract risks from this meeting transcript:\n\n{{transcript}}",
        "inputs": [
            {
                "name": "transcript",
                "type": "TEXT",
                "required": True,
                "description": "Meeting transcript",
            }
        ],
    },
    {
        "name": "Team Discussion Summary",
        "description": "Summarise a Teams channel discussion thread.",
        "business_function": "OPERATIONS",
        "application": "TEAMS",
        "task": "SUMMARISE",
        "goal": "Summarise the channel discussion into themes and consensus.",
        "context": "Busy channels make it hard to stay current; the summary captures the essence.",
        "source": "Use only the supplied channel messages.",
        "expectations": "Provide themes, key viewpoints, any agreement reached and open questions.",
        "audience": "TEAM",
        "tone": "CONCISE",
        "output_format": "BULLET_POINTS",
        "max_length": "SHORT",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["teams", "discussion"],
        "manual_time_minutes": 12,
        "ai_time_minutes": 2,
        "template": "Summarise this Teams discussion:\n\n{{messages}}",
        "inputs": [
            {
                "name": "messages",
                "type": "TEXT",
                "required": True,
                "description": "Channel messages",
            }
        ],
    },
    {
        "name": "Executive Meeting Brief",
        "description": "Prepare a brief for an executive attending a meeting.",
        "business_function": "EXECUTIVE",
        "application": "TEAMS",
        "task": "CREATE",
        "goal": "Create a one-page executive brief for the upcoming meeting.",
        "context": "Executives need context fast: what is happening, what they must know, what is expected of them.",
        "source": "Use only the supplied meeting materials and notes.",
        "expectations": "Produce: meeting purpose, context, key talking points, sensitive items, and recommended positions.",
        "audience": "EXECUTIVE",
        "tone": "CONCISE",
        "output_format": "EXECUTIVE_SUMMARY",
        "max_length": "SHORT",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["teams", "executive", "brief"],
        "manual_time_minutes": 30,
        "ai_time_minutes": 5,
        "template": "Prepare an executive meeting brief from:\n\n{{meeting_materials}}",
        "inputs": [
            {
                "name": "meeting_materials",
                "type": "TEXT",
                "required": True,
                "description": "Meeting materials",
            }
        ],
    },
    {
        "name": "Unresolved Questions",
        "description": "Extract unresolved questions from meetings and discussions.",
        "business_function": "PROJECT_MANAGEMENT",
        "application": "TEAMS",
        "task": "EXTRACT",
        "goal": "List all questions that remain unanswered.",
        "context": "Unresolved questions block progress; tracking them keeps teams honest.",
        "source": "Use only the supplied transcript or thread.",
        "expectations": "Return each question, who asked it, and whether an answer was found.",
        "audience": "TEAM",
        "tone": "CONCISE",
        "output_format": "BULLET_POINTS",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["teams", "questions"],
        "manual_time_minutes": 10,
        "ai_time_minutes": 2,
        "template": "Extract unresolved questions from:\n\n{{discussion}}",
        "inputs": [
            {
                "name": "discussion",
                "type": "TEXT",
                "required": True,
                "description": "Transcript or thread",
            }
        ],
    },
    # ── Word ────────────────────────────────────────────────────────────────
    {
        "name": "Executive Summary",
        "description": "Generate an executive summary from a detailed document.",
        "business_function": "EXECUTIVE",
        "application": "WORD",
        "task": "SUMMARISE",
        "goal": "Produce a concise executive summary of the document.",
        "context": "Senior leaders need the essence of long documents; the summary should support quick decisions.",
        "source": "Use only the supplied document text.",
        "expectations": "One page max: purpose, key findings, risks, recommendations. Use subheadings.",
        "audience": "SENIOR_MANAGEMENT",
        "tone": "PROFESSIONAL",
        "output_format": "EXECUTIVE_SUMMARY",
        "max_length": "SHORT",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["word", "summary", "executive"],
        "manual_time_minutes": 40,
        "ai_time_minutes": 6,
        "template": "Write an executive summary of:\n\n{{document}}",
        "inputs": [
            {
                "name": "document",
                "type": "DOCUMENT",
                "required": True,
                "description": "Document to summarise",
            }
        ],
    },
    {
        "name": "Document Summariser",
        "description": "Summarise any document into a digestible overview.",
        "business_function": "OPERATIONS",
        "application": "WORD",
        "task": "SUMMARISE",
        "goal": "Summarise the document into key sections and main points.",
        "context": "Long documents are rarely read fully; a faithful summary preserves structure and nuance.",
        "source": "Use only the supplied document.",
        "expectations": "Provide an overview paragraph, section-by-section summary, and important details.",
        "audience": "GENERAL",
        "tone": "CONCISE",
        "output_format": "REPORT",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["word", "summary"],
        "manual_time_minutes": 25,
        "ai_time_minutes": 4,
        "template": "Summarise this document:\n\n{{document}}",
        "inputs": [
            {
                "name": "document",
                "type": "DOCUMENT",
                "required": True,
                "description": "Document text",
            }
        ],
    },
    {
        "name": "Requirements Extractor",
        "description": "Extract functional and non-functional requirements from prose.",
        "business_function": "IT",
        "application": "WORD",
        "task": "EXTRACT",
        "goal": "Extract clear requirements from the supplied business prose.",
        "context": "Poor requirements cause rework; extraction normalises and structures them.",
        "source": "Use only the supplied document.",
        "expectations": "Return a numbered list of requirements grouped by functional/non-functional, each with ID, priority and source sentence.",
        "audience": "TECHNICAL",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "LONG",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["word", "requirements", "analysis"],
        "manual_time_minutes": 60,
        "ai_time_minutes": 10,
        "template": "Extract requirements from the following text:\n\n{{document}}",
        "inputs": [
            {
                "name": "document",
                "type": "DOCUMENT",
                "required": True,
                "description": "Requirements prose",
            }
        ],
    },
    {
        "name": "Policy Simplifier",
        "description": "Rewrite complex corporate policies in plain language.",
        "business_function": "HR",
        "application": "WORD",
        "task": "REWRITE",
        "goal": "Rewrite the policy in plain, accessible language.",
        "context": "Employees must understand policies; legal accuracy must be preserved.",
        "source": "Use only the supplied policy text.",
        "expectations": "Keep legal meaning intact, simplify jargon, use short sentences, and flag anything that needs legal review.",
        "audience": "GENERAL",
        "tone": "FRIENDLY",
        "output_format": "NARRATIVE",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "MEDIUM",
        "tags": ["word", "policy", "plain-language"],
        "manual_time_minutes": 45,
        "ai_time_minutes": 8,
        "template": "Rewrite this policy in plain language:\n\n{{policy_text}}",
        "inputs": [
            {
                "name": "policy_text",
                "type": "DOCUMENT",
                "required": True,
                "description": "Policy text",
            }
        ],
    },
    {
        "name": "Document Reviewer",
        "description": "Review a document for clarity, completeness and consistency.",
        "business_function": "OPERATIONS",
        "application": "WORD",
        "task": "ANALYSE",
        "goal": "Review the document and report issues with clarity, completeness and consistency.",
        "context": "Peer review improves document quality before distribution.",
        "source": "Use only the supplied document.",
        "expectations": "List each issue with severity, section reference and suggested fix. Summarise overall quality.",
        "audience": "TEAM",
        "tone": "ANALYTICAL",
        "output_format": "REPORT",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["word", "review"],
        "manual_time_minutes": 35,
        "ai_time_minutes": 6,
        "template": "Review this document:\n\n{{document}}",
        "inputs": [
            {
                "name": "document",
                "type": "DOCUMENT",
                "required": True,
                "description": "Document to review",
            }
        ],
    },
    {
        "name": "Document Comparison",
        "description": "Compare two document versions and summarise differences.",
        "business_function": "OPERATIONS",
        "application": "WORD",
        "task": "COMPARE",
        "goal": "Compare the two document versions and describe substantive differences.",
        "context": "Version control requires clear difference summaries for review.",
        "source": "Use only the two supplied documents.",
        "expectations": "Provide a table of differences by section with a recommendation on which to keep.",
        "audience": "MANAGEMENT",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["word", "compare"],
        "manual_time_minutes": 30,
        "ai_time_minutes": 5,
        "template": "Compare these documents:\n\nDocument A:\n{{document_a}}\n\nDocument B:\n{{document_b}}",
        "inputs": [
            {
                "name": "document_a",
                "type": "DOCUMENT",
                "required": True,
                "description": "First version",
            },
            {
                "name": "document_b",
                "type": "DOCUMENT",
                "required": True,
                "description": "Second version",
            },
        ],
    },
    {
        "name": "Business Case Generator",
        "description": "Draft a structured business case from outline points.",
        "business_function": "FINANCE",
        "application": "WORD",
        "task": "CREATE",
        "goal": "Generate a complete business case from the supplied outline.",
        "context": "Business cases must follow Contoso's investment approval framework.",
        "source": "Use only the supplied outline and constraints.",
        "expectations": "Produce: executive summary, problem statement, options analysis, financials, risks and recommendation.",
        "audience": "EXECUTIVE",
        "tone": "PROFESSIONAL",
        "output_format": "REPORT",
        "max_length": "LONG",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "contains_financial_data": True,
        "tags": ["word", "business-case", "finance"],
        "manual_time_minutes": 120,
        "ai_time_minutes": 15,
        "template": "Generate a business case from this outline:\n\n{{outline}}",
        "inputs": [
            {
                "name": "outline",
                "type": "TEXT",
                "required": True,
                "description": "Business case outline",
            }
        ],
    },
    # ── Excel ───────────────────────────────────────────────────────────────
    {
        "name": "KPI Analysis",
        "description": "Analyse KPI data and explain performance drivers.",
        "business_function": "DATA_ANALYTICS",
        "application": "EXCEL",
        "task": "ANALYSE",
        "goal": "Analyse the KPI dataset and explain what the numbers mean.",
        "context": "The analysis supports monthly business review for leadership.",
        "source": "Use only the supplied KPI dataset.",
        "expectations": "Provide trends, notable variances, likely drivers, and recommended actions. Reference specific values.",
        "audience": "MANAGEMENT",
        "tone": "ANALYTICAL",
        "output_format": "REPORT",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "contains_financial_data": True,
        "tags": ["excel", "kpi", "analysis"],
        "manual_time_minutes": 45,
        "ai_time_minutes": 8,
        "template": "Analyse this KPI dataset:\n\n{{kpi_data}}",
        "inputs": [
            {"name": "kpi_data", "type": "TABLE", "required": True, "description": "KPI dataset"}
        ],
    },
    {
        "name": "Trend Analysis",
        "description": "Identify trends in time-series data.",
        "business_function": "DATA_ANALYTICS",
        "application": "EXCEL",
        "task": "ANALYSE",
        "goal": "Identify trends, seasonality and anomalies in the time series.",
        "context": "Trend insight feeds planning and forecasting activities.",
        "source": "Use only the supplied data.",
        "expectations": "Report direction, magnitude, seasonality, outliers with evidence, and a forward-looking note.",
        "audience": "TECHNICAL",
        "tone": "ANALYTICAL",
        "output_format": "REPORT",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["excel", "trends"],
        "manual_time_minutes": 40,
        "ai_time_minutes": 7,
        "template": "Analyse trends in this data:\n\n{{time_series_data}}",
        "inputs": [
            {
                "name": "time_series_data",
                "type": "TABLE",
                "required": True,
                "description": "Time series data",
            }
        ],
    },
    {
        "name": "Data Quality Assessment",
        "description": "Assess a dataset for data quality problems.",
        "business_function": "DATA_ANALYTICS",
        "application": "EXCEL",
        "task": "ANALYSE",
        "goal": "Assess the supplied dataset for data quality problems.",
        "context": "The dataset will support an enterprise reporting solution, so quality matters.",
        "source": "Use only the supplied dataset and metadata.",
        "expectations": "Assess completeness, accuracy, consistency, uniqueness, validity and referential integrity. For each issue provide column, issue, severity, evidence and recommendation. Do not invent values. Return a structured table.",
        "audience": "TECHNICAL",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["excel", "data-quality"],
        "manual_time_minutes": 60,
        "ai_time_minutes": 10,
        "template": "Assess the data quality of this dataset:\n\n{{dataset}}",
        "inputs": [
            {
                "name": "dataset",
                "type": "TABLE",
                "required": True,
                "description": "Dataset to assess",
            }
        ],
    },
    {
        "name": "Outlier Detection",
        "description": "Identify outliers in a numeric dataset with explanations.",
        "business_function": "DATA_ANALYTICS",
        "application": "EXCEL",
        "task": "ANALYSE",
        "goal": "Identify statistical outliers in the dataset.",
        "context": "Outliers may indicate errors or genuine anomalies; both need investigation.",
        "source": "Use only the supplied dataset.",
        "expectations": "For each outlier: value, expected range, possible cause and recommended action.",
        "audience": "TECHNICAL",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["excel", "outliers"],
        "manual_time_minutes": 30,
        "ai_time_minutes": 5,
        "template": "Detect outliers in this dataset:\n\n{{dataset}}",
        "inputs": [
            {"name": "dataset", "type": "TABLE", "required": True, "description": "Numeric dataset"}
        ],
    },
    {
        "name": "Financial Variance Analysis",
        "description": "Explain budget vs actual variances.",
        "business_function": "FINANCE",
        "application": "EXCEL",
        "task": "ANALYSE",
        "goal": "Analyse budget-to-actual variances and explain their causes.",
        "context": "Monthly variance reporting supports financial control.",
        "source": "Use only the supplied budget and actual figures.",
        "expectations": "Summarise total variance, list material variances by cost centre, propose causes and flag follow-up needed.",
        "audience": "SENIOR_MANAGEMENT",
        "tone": "ANALYTICAL",
        "output_format": "REPORT",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "contains_financial_data": True,
        "tags": ["excel", "finance", "variance"],
        "manual_time_minutes": 50,
        "ai_time_minutes": 8,
        "template": "Analyse the variance between budget and actual:\n\n{{budget_data}}\n\nActual:\n{{actual_data}}",
        "inputs": [
            {
                "name": "budget_data",
                "type": "TABLE",
                "required": True,
                "description": "Budget figures",
            },
            {
                "name": "actual_data",
                "type": "TABLE",
                "required": True,
                "description": "Actual figures",
            },
        ],
    },
    {
        "name": "Dataset Summary",
        "description": "Produce a plain-language summary of a dataset.",
        "business_function": "DATA_ANALYTICS",
        "application": "EXCEL",
        "task": "SUMMARISE",
        "goal": "Describe the dataset in plain language.",
        "context": "Non-technical stakeholders need to understand what the data contains.",
        "source": "Use only the supplied dataset.",
        "expectations": "Describe rows, columns, data types, key patterns and notable values. Avoid jargon.",
        "audience": "GENERAL",
        "tone": "FRIENDLY",
        "output_format": "NARRATIVE",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["excel", "summary"],
        "manual_time_minutes": 25,
        "ai_time_minutes": 4,
        "template": "Summarise this dataset:\n\n{{dataset}}",
        "inputs": [
            {"name": "dataset", "type": "TABLE", "required": True, "description": "Dataset"}
        ],
    },
    {
        "name": "Root Cause Analysis",
        "description": "Perform root cause analysis on operational issues.",
        "business_function": "OPERATIONS",
        "application": "EXCEL",
        "task": "ANALYSE",
        "goal": "Analyse the incident data to identify likely root causes.",
        "context": "Incident trends reveal systemic issues that need fixing at source.",
        "source": "Use only the supplied incident data.",
        "expectations": "Group incidents by category, propose root causes, estimate impact, and recommend corrective actions.",
        "audience": "MANAGEMENT",
        "tone": "ANALYTICAL",
        "output_format": "REPORT",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "MEDIUM",
        "tags": ["excel", "root-cause"],
        "manual_time_minutes": 45,
        "ai_time_minutes": 7,
        "template": "Perform root cause analysis on this incident data:\n\n{{incident_data}}",
        "inputs": [
            {
                "name": "incident_data",
                "type": "TABLE",
                "required": True,
                "description": "Incident data",
            }
        ],
    },
    # ── PowerPoint ──────────────────────────────────────────────────────────
    {
        "name": "Executive Presentation",
        "description": "Outline an executive presentation from source material.",
        "business_function": "EXECUTIVE",
        "application": "POWERPOINT",
        "task": "CREATE",
        "goal": "Create a presentation outline suitable for executives.",
        "context": "Executives want the story: situation, decision, evidence, recommendation.",
        "source": "Use only the supplied material.",
        "expectations": "Produce slide titles plus 3-5 bullet points each: context, analysis, options, recommendation, next steps.",
        "audience": "EXECUTIVE",
        "tone": "CONCISE",
        "output_format": "DECK_OUTLINE",
        "max_length": "LONG",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["powerpoint", "executive"],
        "manual_time_minutes": 90,
        "ai_time_minutes": 12,
        "template": "Create an executive presentation outline from:\n\n{{source_material}}",
        "inputs": [
            {
                "name": "source_material",
                "type": "DOCUMENT",
                "required": True,
                "description": "Source material",
            }
        ],
    },
    {
        "name": "Project Update Deck",
        "description": "Generate a project status update deck.",
        "business_function": "PROJECT_MANAGEMENT",
        "application": "POWERPOINT",
        "task": "CREATE",
        "goal": "Create a project update presentation for stakeholders.",
        "context": "Regular status decks keep stakeholders informed and honest.",
        "source": "Use only the supplied project status data.",
        "expectations": "Slides for: status, milestones, risks, issues, decisions needed, next actions. Use a traffic-light approach.",
        "audience": "STAKEHOLDERS",
        "tone": "CONCISE",
        "output_format": "DECK_OUTLINE",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["powerpoint", "project-status"],
        "manual_time_minutes": 60,
        "ai_time_minutes": 9,
        "template": "Create a project update deck from:\n\n{{project_status}}",
        "inputs": [
            {
                "name": "project_status",
                "type": "TEXT",
                "required": True,
                "description": "Project status data",
            }
        ],
    },
    {
        "name": "Board Presentation",
        "description": "Prepare a board-level presentation with rigorous tone.",
        "business_function": "EXECUTIVE",
        "application": "POWERPOINT",
        "task": "CREATE",
        "goal": "Create a board presentation that is precise, honest and concise.",
        "context": "Board members require fact-based reporting with clear recommendations.",
        "source": "Use only the supplied material.",
        "expectations": "Follow a board narrative: executive summary, performance, risks, governance, ask. Cite evidence where material.",
        "audience": "BOARD",
        "tone": "FORMAL",
        "output_format": "DECK_OUTLINE",
        "max_length": "LONG",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "HIGH",
        "tags": ["powerpoint", "board"],
        "manual_time_minutes": 180,
        "ai_time_minutes": 20,
        "template": "Create a board presentation from:\n\n{{source_material}}",
        "inputs": [
            {
                "name": "source_material",
                "type": "DOCUMENT",
                "required": True,
                "description": "Board materials",
            }
        ],
    },
    {
        "name": "Presentation Summary",
        "description": "Summarise a presentation deck into talking notes.",
        "business_function": "OPERATIONS",
        "application": "POWERPOINT",
        "task": "SUMMARISE",
        "goal": "Summarise the deck into concise talking notes.",
        "context": "Presenters need quick notes that capture the narrative without slides.",
        "source": "Use only the supplied deck content.",
        "expectations": "Produce per-slide one-liners plus overall message and key evidence.",
        "audience": "GENERAL",
        "tone": "CONCISE",
        "output_format": "SPEAKER_NOTES",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["powerpoint", "summary"],
        "manual_time_minutes": 30,
        "ai_time_minutes": 5,
        "template": "Summarise this deck into talking notes:\n\n{{deck_content}}",
        "inputs": [
            {
                "name": "deck_content",
                "type": "DOCUMENT",
                "required": True,
                "description": "Deck content",
            }
        ],
    },
    {
        "name": "Speaker Notes",
        "description": "Write natural speaker notes for slides.",
        "business_function": "OPERATIONS",
        "application": "POWERPOINT",
        "task": "CREATE",
        "goal": "Write natural speaker notes for the slide content.",
        "context": "Notes should sound spoken, not read, and add context to bullets.",
        "source": "Use only the supplied slides.",
        "expectations": "For each slide: 2-4 sentences of spoken text, transition hints and likely questions.",
        "audience": "GENERAL",
        "tone": "FRIENDLY",
        "output_format": "SPEAKER_NOTES",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["powerpoint", "speaker-notes"],
        "manual_time_minutes": 40,
        "ai_time_minutes": 6,
        "template": "Write speaker notes for:\n\n{{slides}}",
        "inputs": [
            {"name": "slides", "type": "DOCUMENT", "required": True, "description": "Slide content"}
        ],
    },
    {
        "name": "Convert Report to Slides",
        "description": "Turn a written report into a slide deck outline.",
        "business_function": "OPERATIONS",
        "application": "POWERPOINT",
        "task": "TRANSFORM",
        "goal": "Convert the report into a presentation outline.",
        "context": "Reports become decks often; the conversion must preserve the narrative.",
        "source": "Use only the supplied report.",
        "expectations": "Map each report section to slides with reduced text and key visuals.",
        "audience": "MANAGEMENT",
        "tone": "CONCISE",
        "output_format": "DECK_OUTLINE",
        "max_length": "LONG",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["powerpoint", "transform"],
        "manual_time_minutes": 75,
        "ai_time_minutes": 10,
        "template": "Convert this report to slides:\n\n{{report}}",
        "inputs": [
            {
                "name": "report",
                "type": "DOCUMENT",
                "required": True,
                "description": "Report to convert",
            }
        ],
    },
    # ── Project Management ──────────────────────────────────────────────────
    {
        "name": "Project Status",
        "description": "Write a project status update from project data.",
        "business_function": "PROJECT_MANAGEMENT",
        "application": "TEAMS",
        "task": "CREATE",
        "goal": "Write a clear project status update.",
        "context": "Status updates must be honest about progress and flag issues early.",
        "source": "Use only the supplied project data.",
        "expectations": "Cover: current status, milestones, risks, issues, decisions needed and next steps. Use traffic-light status.",
        "audience": "STAKEHOLDERS",
        "tone": "CONCISE",
        "output_format": "REPORT",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["project", "status"],
        "manual_time_minutes": 40,
        "ai_time_minutes": 6,
        "template": "Write a project status update from:\n\n{{project_data}}",
        "inputs": [
            {
                "name": "project_data",
                "type": "TEXT",
                "required": True,
                "description": "Project data",
            }
        ],
    },
    {
        "name": "Project Risk Assessment",
        "description": "Assess project risks from the risk register.",
        "business_function": "RISK",
        "application": "EXCEL",
        "task": "ANALYSE",
        "goal": "Assess the project risks and prioritise them.",
        "context": "Risk exposure drives mitigation and executive attention.",
        "source": "Use only the supplied risk register.",
        "expectations": "Score each risk (probability × impact), list top risks, propose mitigations and owners.",
        "audience": "MANAGEMENT",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "HIGH",
        "tags": ["project", "risk"],
        "manual_time_minutes": 60,
        "ai_time_minutes": 10,
        "template": "Assess risks in this register:\n\n{{risk_register}}",
        "inputs": [
            {
                "name": "risk_register",
                "type": "TABLE",
                "required": True,
                "description": "Risk register",
            }
        ],
    },
    {
        "name": "Issue Analysis",
        "description": "Analyse project issues and recommend resolutions.",
        "business_function": "PROJECT_MANAGEMENT",
        "application": "WORD",
        "task": "ANALYSE",
        "goal": "Analyse the project issues and recommend resolutions.",
        "context": "Unresolved issues block delivery; analysis supports triage.",
        "source": "Use only the supplied issue list.",
        "expectations": "For each issue: impact, severity, root cause, recommended resolution, owner, deadline.",
        "audience": "MANAGEMENT",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "MEDIUM",
        "tags": ["project", "issues"],
        "manual_time_minutes": 45,
        "ai_time_minutes": 7,
        "template": "Analyse these project issues:\n\n{{issues}}",
        "inputs": [
            {"name": "issues", "type": "TEXT", "required": True, "description": "List of issues"}
        ],
    },
    {
        "name": "Decision Brief",
        "description": "Prepare a decision brief for a project decision.",
        "business_function": "PROJECT_MANAGEMENT",
        "application": "WORD",
        "task": "CREATE",
        "goal": "Prepare a concise decision brief with options and recommendation.",
        "context": "Good decisions need a clear, unbiased brief.",
        "source": "Use only the supplied context and options.",
        "expectations": "Provide: decision required, background, options with pros/cons, recommendation, and success criteria.",
        "audience": "MANAGEMENT",
        "tone": "PROFESSIONAL",
        "output_format": "DECISION_BRIEF",
        "max_length": "SHORT",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["project", "decision"],
        "manual_time_minutes": 60,
        "ai_time_minutes": 8,
        "template": "Prepare a decision brief:\n\n{{decision_context}}",
        "inputs": [
            {
                "name": "decision_context",
                "type": "TEXT",
                "required": True,
                "description": "Decision context",
            }
        ],
    },
    {
        "name": "Action Tracker",
        "description": "Consolidate actions from multiple sources into a tracker.",
        "business_function": "PROJECT_MANAGEMENT",
        "application": "EXCEL",
        "task": "EXTRACT",
        "goal": "Consolidate action items from the supplied sources into a tracker.",
        "context": "Actions live across meetings and emails; the tracker consolidates them.",
        "source": "Use only the supplied sources.",
        "expectations": "Return a table of actions with ID, description, owner, due date, status and source.",
        "audience": "TEAM",
        "tone": "CONCISE",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["project", "actions"],
        "manual_time_minutes": 30,
        "ai_time_minutes": 5,
        "template": "Consolidate actions from:\n\n{{sources}}",
        "inputs": [
            {
                "name": "sources",
                "type": "TEXT",
                "required": True,
                "description": "Sources of actions",
            }
        ],
    },
    {
        "name": "Project Health Assessment",
        "description": "Assess overall project health across multiple dimensions.",
        "business_function": "PROJECT_MANAGEMENT",
        "application": "GENERIC_AI",
        "task": "ANALYSE",
        "goal": "Assess the project's overall health.",
        "context": "Health assessment gives an early warning view across the portfolio.",
        "source": "Use only the supplied project data.",
        "expectations": "Score scope, schedule, budget, quality, risk, team and governance. Provide an overall health rating with rationale.",
        "audience": "MANAGEMENT",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["project", "health"],
        "manual_time_minutes": 40,
        "ai_time_minutes": 6,
        "template": "Assess the health of this project:\n\n{{project_data}}",
        "inputs": [
            {
                "name": "project_data",
                "type": "TEXT",
                "required": True,
                "description": "Project data",
            }
        ],
    },
    # ── Data & Analytics ────────────────────────────────────────────────────
    {
        "name": "Data Requirements Extractor",
        "description": "Extract data requirements from business requirements.",
        "business_function": "DATA_ANALYTICS",
        "application": "WORD",
        "task": "EXTRACT",
        "goal": "Extract data requirements from the business requirements document.",
        "context": "Data delivery starts with clear requirements.",
        "source": "Use only the supplied requirements document.",
        "expectations": "List data entities, attributes, granularity, freshness, retention and access requirements.",
        "audience": "TECHNICAL",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "LONG",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["data", "requirements"],
        "manual_time_minutes": 60,
        "ai_time_minutes": 10,
        "template": "Extract data requirements from:\n\n{{requirements_doc}}",
        "inputs": [
            {
                "name": "requirements_doc",
                "type": "DOCUMENT",
                "required": True,
                "description": "Requirements document",
            }
        ],
    },
    {
        "name": "Data Quality Analyst",
        "description": "Assess data quality and recommend remediation.",
        "business_function": "DATA_ANALYTICS",
        "application": "EXCEL",
        "task": "ANALYSE",
        "goal": "Assess data quality and recommend remediation.",
        "context": "The dataset feeds analytics; quality problems must be understood.",
        "source": "Use only the supplied dataset.",
        "expectations": "Provide a quality scorecard per dimension with evidence and ranked remediation actions.",
        "audience": "TECHNICAL",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["data", "quality"],
        "manual_time_minutes": 50,
        "ai_time_minutes": 8,
        "template": "Analyse data quality for:\n\n{{dataset}}",
        "inputs": [
            {"name": "dataset", "type": "TABLE", "required": True, "description": "Dataset"}
        ],
    },
    {
        "name": "Data Dictionary Generator",
        "description": "Generate a data dictionary from table/column metadata.",
        "business_function": "DATA_ANALYTICS",
        "application": "EXCEL",
        "task": "CREATE",
        "goal": "Generate a data dictionary from the supplied metadata.",
        "context": "A data dictionary standardises understanding across teams.",
        "source": "Use only the supplied table/column metadata.",
        "expectations": "Produce per-table: column, type, description, example, business term mapping and constraints.",
        "audience": "TECHNICAL",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "LONG",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["data", "dictionary"],
        "manual_time_minutes": 90,
        "ai_time_minutes": 12,
        "template": "Generate a data dictionary from:\n\n{{metadata}}",
        "inputs": [
            {
                "name": "metadata",
                "type": "JSON",
                "required": True,
                "description": "Table/column metadata",
            }
        ],
    },
    {
        "name": "Data Model Reviewer",
        "description": "Review a data model for correctness and best practice.",
        "business_function": "DATA_ANALYTICS",
        "application": "WORD",
        "task": "ANALYSE",
        "goal": "Review the data model for correctness, completeness and best practice.",
        "context": "Modelling review catches issues before implementation.",
        "source": "Use only the supplied model definition.",
        "expectations": "Check entities, relationships, keys, normalisation, naming and documentation. Provide a fix list.",
        "audience": "TECHNICAL",
        "tone": "ANALYTICAL",
        "output_format": "REPORT",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["data", "model"],
        "manual_time_minutes": 75,
        "ai_time_minutes": 12,
        "template": "Review this data model:\n\n{{model_definition}}",
        "inputs": [
            {
                "name": "model_definition",
                "type": "TEXT",
                "required": True,
                "description": "Model definition",
            }
        ],
    },
    {
        "name": "SQL Explanation",
        "description": "Explain complex SQL queries in plain language.",
        "business_function": "IT",
        "application": "GENERIC_AI",
        "task": "EXPLAIN",
        "goal": "Explain the SQL query in plain language.",
        "context": "Teams need to understand and trust existing SQL.",
        "source": "Use only the supplied SQL.",
        "expectations": "Explain the query intent, joins, filters, aggregations, performance notes and potential issues.",
        "audience": "TECHNICAL",
        "tone": "ANALYTICAL",
        "output_format": "NARRATIVE",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["sql", "explain"],
        "manual_time_minutes": 25,
        "ai_time_minutes": 4,
        "template": "Explain this SQL query:\n\n{{sql_query}}",
        "inputs": [
            {"name": "sql_query", "type": "TEXT", "required": True, "description": "SQL query"}
        ],
    },
    # ── Executive ───────────────────────────────────────────────────────────
    {
        "name": "Executive Brief",
        "description": "Prepare a one-page executive brief on a topic.",
        "business_function": "EXECUTIVE",
        "application": "WORD",
        "task": "CREATE",
        "goal": "Prepare a one-page executive brief on the topic.",
        "context": "Executives need fast, reliable context before decisions.",
        "source": "Use only the supplied material.",
        "expectations": "One page: summary, key facts, implications, risks, recommendation.",
        "audience": "EXECUTIVE",
        "tone": "CONCISE",
        "output_format": "EXECUTIVE_SUMMARY",
        "max_length": "SHORT",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["executive", "brief"],
        "manual_time_minutes": 45,
        "ai_time_minutes": 6,
        "template": "Prepare an executive brief on:\n\n{{topic_material}}",
        "inputs": [
            {
                "name": "topic_material",
                "type": "TEXT",
                "required": True,
                "description": "Topic material",
            }
        ],
    },
    {
        "name": "Decision Memo",
        "description": "Draft a decision memo with options and a recommendation.",
        "business_function": "EXECUTIVE",
        "application": "WORD",
        "task": "CREATE",
        "goal": "Draft a decision memo that enables a clear decision.",
        "context": "Memos must be persuasive, honest and decision-oriented.",
        "source": "Use only the supplied information.",
        "expectations": "Structure: decision requested, background, options, trade-offs, recommendation, next steps.",
        "audience": "EXECUTIVE",
        "tone": "FORMAL",
        "output_format": "MEMORANDUM",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["executive", "memo"],
        "manual_time_minutes": 60,
        "ai_time_minutes": 8,
        "template": "Draft a decision memo:\n\n{{memo_inputs}}",
        "inputs": [
            {"name": "memo_inputs", "type": "TEXT", "required": True, "description": "Memo inputs"}
        ],
    },
    {
        "name": "Management Summary",
        "description": "Summarise material for a management audience.",
        "business_function": "EXECUTIVE",
        "application": "WORD",
        "task": "SUMMARISE",
        "goal": "Summarise the material for a management audience.",
        "context": "Managers need highlights and implications, not full detail.",
        "source": "Use only the supplied material.",
        "expectations": "Provide highlights, implications, and recommended actions with owners.",
        "audience": "MANAGEMENT",
        "tone": "CONCISE",
        "output_format": "EXECUTIVE_SUMMARY",
        "max_length": "SHORT",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["executive", "summary"],
        "manual_time_minutes": 35,
        "ai_time_minutes": 5,
        "template": "Summarise the following for management:\n\n{{material}}",
        "inputs": [
            {
                "name": "material",
                "type": "TEXT",
                "required": True,
                "description": "Material to summarise",
            }
        ],
    },
    {
        "name": "Board Briefing",
        "description": "Prepare a board briefing on a strategic topic.",
        "business_function": "EXECUTIVE",
        "application": "WORD",
        "task": "CREATE",
        "goal": "Prepare a board briefing on the strategic topic.",
        "context": "Board briefings require precision, evidence and a clear position.",
        "source": "Use only the supplied material.",
        "expectations": "Cover: situation, analysis, risks, governance considerations and the board ask.",
        "audience": "BOARD",
        "tone": "FORMAL",
        "output_format": "EXECUTIVE_SUMMARY",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "HIGH",
        "tags": ["executive", "board"],
        "manual_time_minutes": 120,
        "ai_time_minutes": 15,
        "template": "Prepare a board briefing on:\n\n{{topic_material}}",
        "inputs": [
            {
                "name": "topic_material",
                "type": "TEXT",
                "required": True,
                "description": "Topic material",
            }
        ],
    },
    # ── Sales / Marketing / Legal / HR / IT / Finance ───────────────────────
    {
        "name": "Sales Follow-up Email",
        "description": "Draft a sales follow-up email after a meeting.",
        "business_function": "SALES",
        "application": "OUTLOOK",
        "task": "CREATE",
        "goal": "Draft a sales follow-up email after the meeting.",
        "context": "Timely, professional follow-up moves deals forward.",
        "source": "Use only the supplied meeting notes.",
        "expectations": "Recap the meeting, confirm next steps, propose the next touchpoint and mirror the customer's language.",
        "audience": "CUSTOMER",
        "tone": "PROFESSIONAL",
        "output_format": "EMAIL",
        "max_length": "SHORT",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "LOW",
        "contains_customer_data": True,
        "tags": ["sales", "email"],
        "manual_time_minutes": 15,
        "ai_time_minutes": 3,
        "template": "Draft a sales follow-up email from:\n\n{{meeting_notes}}",
        "inputs": [
            {
                "name": "meeting_notes",
                "type": "TEXT",
                "required": True,
                "description": "Meeting notes",
            }
        ],
    },
    {
        "name": "Marketing Campaign Brief",
        "description": "Draft a marketing campaign brief.",
        "business_function": "MARKETING",
        "application": "WORD",
        "task": "CREATE",
        "goal": "Draft a marketing campaign brief.",
        "context": "A clear brief keeps agencies and teams aligned.",
        "source": "Use only the supplied campaign inputs.",
        "expectations": "Cover: objectives, audience, message, channels, timeline, budget and success metrics.",
        "audience": "TEAM",
        "tone": "PROFESSIONAL",
        "output_format": "REPORT",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["marketing", "campaign"],
        "manual_time_minutes": 60,
        "ai_time_minutes": 9,
        "template": "Draft a marketing campaign brief:\n\n{{campaign_inputs}}",
        "inputs": [
            {
                "name": "campaign_inputs",
                "type": "TEXT",
                "required": True,
                "description": "Campaign inputs",
            }
        ],
    },
    {
        "name": "Legal Clause Reviewer",
        "description": "Review a contract clause and flag concerns.",
        "business_function": "LEGAL",
        "application": "WORD",
        "task": "ANALYSE",
        "goal": "Review the clause and flag legal and business concerns.",
        "context": "Clauses must be reviewed consistently; this is decision support, not legal advice.",
        "source": "Use only the supplied clause.",
        "expectations": "Identify key obligations, risks, ambiguities, missing terms and recommended redlines.",
        "audience": "TECHNICAL",
        "tone": "ANALYTICAL",
        "output_format": "REPORT",
        "max_length": "MEDIUM",
        "data_classification": "RESTRICTED",
        "risk_level": "HIGH",
        "requires_approval": True,
        "tags": ["legal", "contract"],
        "manual_time_minutes": 45,
        "ai_time_minutes": 8,
        "template": "Review this contract clause:\n\n{{clause}}",
        "inputs": [
            {"name": "clause", "type": "TEXT", "required": True, "description": "Clause text"}
        ],
    },
    {
        "name": "Job Description Writer",
        "description": "Draft a job description from role inputs.",
        "business_function": "HR",
        "application": "WORD",
        "task": "CREATE",
        "goal": "Draft a clear, inclusive job description.",
        "context": "Job descriptions attract the right candidates and set expectations.",
        "source": "Use only the supplied role inputs.",
        "expectations": "Cover: role purpose, responsibilities, requirements, culture and benefits. Use inclusive language.",
        "audience": "GENERAL",
        "tone": "PROFESSIONAL",
        "output_format": "REPORT",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["hr", "job-description"],
        "manual_time_minutes": 60,
        "ai_time_minutes": 8,
        "template": "Draft a job description:\n\n{{role_inputs}}",
        "inputs": [
            {"name": "role_inputs", "type": "TEXT", "required": True, "description": "Role inputs"}
        ],
    },
    {
        "name": "Vendor Assessment",
        "description": "Assess vendors against criteria from a comparison dataset.",
        "business_function": "PROCUREMENT",
        "application": "EXCEL",
        "task": "COMPARE",
        "goal": "Assess and compare the vendors against the scoring criteria.",
        "context": "Vendor selection should be evidence-based and defensible.",
        "source": "Use only the supplied vendor data.",
        "expectations": "Score each vendor per criterion, produce a ranked comparison and note data gaps.",
        "audience": "MANAGEMENT",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["procurement", "vendors"],
        "manual_time_minutes": 60,
        "ai_time_minutes": 9,
        "template": "Assess these vendors:\n\n{{vendor_data}}",
        "inputs": [
            {
                "name": "vendor_data",
                "type": "TABLE",
                "required": True,
                "description": "Vendor comparison data",
            }
        ],
    },
    {
        "name": "Meeting Invite Draft",
        "description": "Draft a clear meeting invite with agenda.",
        "business_function": "OPERATIONS",
        "application": "OUTLOOK",
        "task": "CREATE",
        "goal": "Draft a meeting invite with a clear agenda.",
        "context": "Good invites ensure productive meetings with the right attendees.",
        "source": "Use only the supplied meeting details.",
        "expectations": "Include: purpose, agenda items with timeboxes, pre-reading, and expected outcomes.",
        "audience": "TEAM",
        "tone": "PROFESSIONAL",
        "output_format": "EMAIL",
        "max_length": "SHORT",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["meeting", "invite"],
        "manual_time_minutes": 10,
        "ai_time_minutes": 2,
        "template": "Draft a meeting invite:\n\n{{meeting_details}}",
        "inputs": [
            {
                "name": "meeting_details",
                "type": "TEXT",
                "required": True,
                "description": "Meeting details",
            }
        ],
    },
    {
        "name": "Incident Report Writer",
        "description": "Write a structured incident report from raw notes.",
        "business_function": "IT",
        "application": "WORD",
        "task": "CREATE",
        "goal": "Write a structured incident report from the raw notes.",
        "context": "Incident reports need a standard structure for review and learning.",
        "source": "Use only the supplied notes.",
        "expectations": "Cover: summary, timeline, impact, root cause, actions taken, recommendations and lessons.",
        "audience": "MANAGEMENT",
        "tone": "ANALYTICAL",
        "output_format": "REPORT",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["it", "incident"],
        "manual_time_minutes": 60,
        "ai_time_minutes": 9,
        "template": "Write an incident report from:\n\n{{incident_notes}}",
        "inputs": [
            {
                "name": "incident_notes",
                "type": "TEXT",
                "required": True,
                "description": "Incident notes",
            }
        ],
    },
    {
        "name": "Employee Feedback Summariser",
        "description": "Summarise employee feedback into themes and actions.",
        "business_function": "HR",
        "application": "WORD",
        "task": "SUMMARISE",
        "goal": "Summarise employee feedback into themes and actions.",
        "context": "Survey and feedback data should drive people decisions.",
        "source": "Use only the supplied feedback.",
        "expectations": "Group feedback into themes with sentiment, frequency, evidence and recommended actions.",
        "audience": "MANAGEMENT",
        "tone": "ANALYTICAL",
        "output_format": "REPORT",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "contains_pii": True,
        "tags": ["hr", "feedback"],
        "manual_time_minutes": 40,
        "ai_time_minutes": 6,
        "template": "Summarise employee feedback:\n\n{{feedback}}",
        "inputs": [
            {"name": "feedback", "type": "TEXT", "required": True, "description": "Feedback text"}
        ],
    },
    {
        "name": "Budget Narrative",
        "description": "Write a plain-language narrative for a budget submission.",
        "business_function": "FINANCE",
        "application": "WORD",
        "task": "CREATE",
        "goal": "Write a plain-language narrative for the budget submission.",
        "context": "Budget narratives explain the numbers to non-finance decision makers.",
        "source": "Use only the supplied budget figures.",
        "expectations": "Explain the ask, drivers, assumptions, risks and the impact of not funding.",
        "audience": "SENIOR_MANAGEMENT",
        "tone": "PROFESSIONAL",
        "output_format": "REPORT",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "contains_financial_data": True,
        "tags": ["finance", "budget"],
        "manual_time_minutes": 60,
        "ai_time_minutes": 9,
        "template": "Write a budget narrative for:\n\n{{budget_figures}}",
        "inputs": [
            {
                "name": "budget_figures",
                "type": "TABLE",
                "required": True,
                "description": "Budget figures",
            }
        ],
    },
    {
        "name": "Competitor Analysis",
        "description": "Analyse competitor positioning from research notes.",
        "business_function": "MARKETING",
        "application": "WORD",
        "task": "ANALYSE",
        "goal": "Analyse competitor positioning from the research notes.",
        "context": "Competitive insight informs messaging and strategy.",
        "source": "Use only the supplied research notes.",
        "expectations": "Compare positioning, pricing, strengths, weaknesses and implications for Contoso.",
        "audience": "MANAGEMENT",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["marketing", "competitors"],
        "manual_time_minutes": 45,
        "ai_time_minutes": 7,
        "template": "Analyse competitor positioning:\n\n{{research_notes}}",
        "inputs": [
            {
                "name": "research_notes",
                "type": "TEXT",
                "required": True,
                "description": "Research notes",
            }
        ],
    },
    {
        "name": "IT Support Triage",
        "description": "Triage IT support tickets by priority and category.",
        "business_function": "IT",
        "application": "GENERIC_AI",
        "task": "CLASSIFY",
        "goal": "Triage the support tickets by priority and category.",
        "context": "Support queues need fast, consistent triage.",
        "source": "Use only the supplied tickets.",
        "expectations": "For each ticket: category, priority, likely resolution area and SLA impact.",
        "audience": "TEAM",
        "tone": "CONCISE",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["it", "support"],
        "manual_time_minutes": 25,
        "ai_time_minutes": 4,
        "template": "Triage these support tickets:\n\n{{tickets}}",
        "inputs": [{"name": "tickets", "type": "TEXT", "required": True, "description": "Tickets"}],
    },
    {
        "name": "Onboarding Plan",
        "description": "Create a new-hire onboarding plan.",
        "business_function": "HR",
        "application": "WORD",
        "task": "CREATE",
        "goal": "Create a practical onboarding plan for a new hire.",
        "context": "Structured onboarding improves retention and time to productivity.",
        "source": "Use only the supplied role and team inputs.",
        "expectations": "Produce a week-by-week plan covering systems access, training, introductions and milestones.",
        "audience": "GENERAL",
        "tone": "SUPPORTIVE",
        "output_format": "REPORT",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["hr", "onboarding"],
        "manual_time_minutes": 50,
        "ai_time_minutes": 7,
        "template": "Create an onboarding plan:\n\n{{onboarding_inputs}}",
        "inputs": [
            {
                "name": "onboarding_inputs",
                "type": "TEXT",
                "required": True,
                "description": "Role/team inputs",
            }
        ],
    },
    {
        "name": "Translate Executive Memo",
        "description": "Translate an executive memo into a target language.",
        "business_function": "OPERATIONS",
        "application": "WORD",
        "task": "TRANSLATE",
        "goal": "Translate the memo into the target language while preserving tone.",
        "context": "Global teams need faithful, professional translations.",
        "source": "Use only the supplied memo.",
        "expectations": "Provide the translation plus a short note on any terms left untranslated or ambiguous.",
        "audience": "GENERAL",
        "tone": "PROFESSIONAL",
        "output_format": "NARRATIVE",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "tags": ["translate"],
        "manual_time_minutes": 30,
        "ai_time_minutes": 5,
        "template": "Translate this memo to {{target_language}}:\n\n{{memo}}",
        "inputs": [
            {
                "name": "target_language",
                "type": "TEXT",
                "required": True,
                "description": "Target language",
            },
            {"name": "memo", "type": "TEXT", "required": True, "description": "Memo to translate"},
        ],
    },
    {
        "name": "Process Improvement Ideas",
        "description": "Suggest process improvement ideas from current-state description.",
        "business_function": "OPERATIONS",
        "application": "GENERIC_AI",
        "task": "RECOMMEND",
        "goal": "Suggest practical process improvement ideas.",
        "context": "Continuous improvement targets reduce waste and risk.",
        "source": "Use only the supplied current-state description.",
        "expectations": "For each idea: expected benefit, effort, risk, owners and quick wins.",
        "audience": "MANAGEMENT",
        "tone": "ANALYTICAL",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["operations", "improvement"],
        "manual_time_minutes": 45,
        "ai_time_minutes": 7,
        "template": "Suggest process improvements for:\n\n{{current_state}}",
        "inputs": [
            {
                "name": "current_state",
                "type": "TEXT",
                "required": True,
                "description": "Current-state description",
            }
        ],
    },
    {
        "name": "Stakeholder Communication Plan",
        "description": "Draft a stakeholder communication plan.",
        "business_function": "PROJECT_MANAGEMENT",
        "application": "WORD",
        "task": "CREATE",
        "goal": "Draft a stakeholder communication plan.",
        "context": "Structured communication keeps stakeholders engaged and informed.",
        "source": "Use only the supplied stakeholder inputs.",
        "expectations": "Produce: stakeholder list, interest/influence mapping, message, channel, frequency and owner per group.",
        "audience": "MANAGEMENT",
        "tone": "PROFESSIONAL",
        "output_format": "TABLE",
        "max_length": "MEDIUM",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["project", "communication"],
        "manual_time_minutes": 50,
        "ai_time_minutes": 8,
        "template": "Draft a stakeholder communication plan:\n\n{{stakeholder_inputs}}",
        "inputs": [
            {
                "name": "stakeholder_inputs",
                "type": "TEXT",
                "required": True,
                "description": "Stakeholder inputs",
            }
        ],
    },
    {
        "name": "Customer Complaint Response",
        "description": "Draft a resolution-focused response to a complaint.",
        "business_function": "CUSTOMER_SERVICE",
        "application": "OUTLOOK",
        "task": "CREATE",
        "goal": "Draft a response that acknowledges and resolves the complaint.",
        "context": "Complaint responses must be empathetic, factual and compliant.",
        "source": "Use only the complaint and account context.",
        "expectations": "Acknowledge the issue, apologise appropriately, state the resolution or next step, and set expectations.",
        "audience": "CUSTOMER",
        "tone": "SUPPORTIVE",
        "output_format": "EMAIL",
        "max_length": "MEDIUM",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "contains_customer_data": True,
        "tags": ["customer", "complaint"],
        "manual_time_minutes": 25,
        "ai_time_minutes": 4,
        "template": "Draft a complaint response for:\n\n{{complaint}}",
        "inputs": [
            {
                "name": "complaint",
                "type": "TEXT",
                "required": True,
                "description": "Complaint details",
            }
        ],
    },
    {
        "name": "Internal Comms Announcement",
        "description": "Write an internal announcement for company-wide communication.",
        "business_function": "HR",
        "application": "OUTLOOK",
        "task": "CREATE",
        "goal": "Write a clear internal announcement.",
        "context": "Internal announcements must be transparent and consistent with company voice.",
        "source": "Use only the supplied announcement details.",
        "expectations": "Include: headline, what changed, why, impact on employees, and where to find more.",
        "audience": "GENERAL",
        "tone": "FRIENDLY",
        "output_format": "EMAIL",
        "max_length": "SHORT",
        "data_classification": "INTERNAL",
        "risk_level": "LOW",
        "tags": ["internal-comms"],
        "manual_time_minutes": 20,
        "ai_time_minutes": 3,
        "template": "Write an internal announcement:\n\n{{announcement_details}}",
        "inputs": [
            {
                "name": "announcement_details",
                "type": "TEXT",
                "required": True,
                "description": "Announcement details",
            }
        ],
    },
    {
        "name": "Quarterly Business Review",
        "description": "Prepare a quarterly business review summary.",
        "business_function": "FINANCE",
        "application": "POWERPOINT",
        "task": "ANALYSE",
        "goal": "Prepare a quarterly business review summary.",
        "context": "The QBR must connect performance to strategy for leadership.",
        "source": "Use only the supplied quarterly data.",
        "expectations": "Cover: performance vs targets, key wins, challenges, forecasts and leadership asks.",
        "audience": "SENIOR_MANAGEMENT",
        "tone": "ANALYTICAL",
        "output_format": "DECK_OUTLINE",
        "max_length": "LONG",
        "data_classification": "CONFIDENTIAL",
        "risk_level": "MEDIUM",
        "contains_financial_data": True,
        "tags": ["finance", "qbr"],
        "manual_time_minutes": 120,
        "ai_time_minutes": 15,
        "template": "Prepare a quarterly business review from:\n\n{{quarterly_data}}",
        "inputs": [
            {
                "name": "quarterly_data",
                "type": "TEXT",
                "required": True,
                "description": "Quarterly data",
            }
        ],
    },
]
